name: Test Gitops CI

on:
  push:
    branches: ["test/gitops"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set OWNER_LOWER & IMAGE_TAG
        id: vars
        run: |
          echo "OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          TAG=sha-${GITHUB_SHA::7}
          echo "IMAGE_TAG=$TAG" >> "$GITHUB_OUTPUT"

      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: SemgaTeam/configs
          ssh-key: ${{ secrets.GITOPS_DEPLOY_KEY }}
          path: gitops

      - name: Update image tag
        run: |
          cd gitops
          yq -i '
            .image.tag = "${{ steps.vars.outputs.IMAGE_TAG }}"
          ' apps/landing/prod/values.yaml

          cat apps/landing/prod/values.yaml
