name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set OWNER_LOWER & IMAGE_TAG
        id: vars
        run: |
          echo "OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          TAG=sha-${GITHUB_SHA::7}
          echo "IMAGE_TAG=$TAG" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.vars.outputs.OWNER_LOWER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/${{ steps.vars.outputs.OWNER_LOWER }}/landing:${{ steps.vars.outputs.IMAGE_TAG }} \
            -t ghcr.io/${{ steps.vars.outputs.OWNER_LOWER }}/landing:latest \
            --push \
            .
