name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t landing:latest .

      - name: Save image to tar
        run: |
          mkdir -p artifacts
          docker save landing:latest -o artifacts/landing.tar

      - name: Compress tar to tar.gz
        run: |
          gzip -9 artifacts/landing.tar
          ls -lh artifacts
          chmod 644 artifacts/landing.tar.gz

      - name: Upload image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "artifacts/landing.tar.gz"
          target: "/home/${{ secrets.SERVER_USER }}/deploy/"

      - name: Run remote deploy script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/deploy

            gzip -d landing.tar.gz

            docker load -i landing.tar

            docker tag landing:latest localhost:5000/landing:latest
            docker push localhost:5000/landing:latest

            cd ~/services/landing
            docker-compose pull
            docker-compose down
            docker-compose up -d
