name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set OWNER_LOWER
        id: vars
        run: |
          echo "OWNER_LOWER=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ steps.vars.outputs.OWNER_LOWER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        run: |
          TAG=sha-${GITHUB_SHA::7}
          
          docker buildx build \
            --platform linux/amd64 \
            -t ghcr.io/${{ steps.vars.outputs.OWNER_LOWER }}/landing:$TAG \
            -t ghcr.io/${{ steps.vars.outputs.OWNER_LOWER }}/landing:latest \
            --push \
            .

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            cd ~/services/landing 
            IMAGE_TAG=sha-${GITHUB_SHA::7}
            docker compose pull
            docker compose up -d
